import { defineConfig, devices } from '@playwright/test'

// The e2e suite runs against df-dev-server, not a bare vite with DATA_FAIR_TEST:
// tests/e2e reads the live configuration from the dev-server `GET /config`
// endpoint (fed by .dev-config.json) and derives every expectation from it.
//
// Ports come from the .env generated by df-dev-env (`npm run test` /
// `npm run test-e2e` are prefixed with `df-dev-env && dotenv --`).
// df-dev-server proxies the app to vite on APP_PORT, so run `npm run dev`
// (or at least `npm run dev-app`) in another terminal before `npm run test-e2e`.
// `reuseExistingServer: !process.env.CI` reuses the dev-server already running locally.
const PORT = Number(process.env.DEV_SERVER_PORT ?? 5888)
const BASE_URL = `http://localhost:${PORT}`

// webServer is global to the config: conditioning it avoids starting the
// dev-server on a purely unit run. Playwright accepts both --project x and --project=x.
function getProjectArgs () {
  const projects: string[] = []
  for (let i = 0; i < process.argv.length; i++) {
    const arg = process.argv[i]
    if (arg === '--project') projects.push(process.argv[i + 1])
    else if (arg.startsWith('--project=')) projects.push(arg.slice('--project='.length))
  }
  return projects
}
const projectArgs = getProjectArgs()
const isUnitOnly = projectArgs.length > 0 && projectArgs.every(p => p === 'unit')

export default defineConfig({
  testMatch: /.*\.spec\.ts$/,
  fullyParallel: true,
  // no per-project workers in Playwright: the browser suite runs alone, the unit project keeps the default pool
  workers: isUnitOnly ? undefined : 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [['list'], ['html', { open: 'never' }]],
  outputDir: './tests/output',
  webServer: isUnitOnly
    ? undefined
    : {
        command: 'npm run dev-server',
        url: `${BASE_URL}/app/`,
        reuseExistingServer: !process.env.CI,
        timeout: 60 * 1000,
        stdout: 'ignore',
        stderr: 'pipe'
      },
  projects: [
    {
      name: 'unit',
      testDir: './tests/unit'
    },
    {
      name: 'e2e',
      testDir: './tests/e2e',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure'
      }
    }
  ]
})
